database:
  params: useSSL=false&allowPublicKeyRetrieval=true&profileSQL=true

spring:
  mvc:
    throw-exception-if-no-handler-found: true
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
  web:
    resources:
      add-mappings: false
  jackson:
    date-format: ${spring.mvc.format.date-time}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?${database.params}
    username: hoyoung
    password:
    hikari:
      driver-class-name: ${spring.datasource.driver-class-name}
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
        maximumPoolSize: 10
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /docs.do
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    doc-expansion: none
    tags-sorter: alpha
  model-and-view-allowed: true

logging:
  level:
    com.zaxxer.hikari: trace
    com.zaxxer.hikari.HikariConfig: debug
    com.zaxxer.hikari.pool.HikariPool: debug
    org.apache.ibatis: debug
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql.BasicBinder: debug
    org.springframework.transaction: debug
    org.springframework.orm.jpa: debug
    com.mysql.cj.log.StandardLogger: info